### ISSUE TITLE
Strange behavior with get_data!()

### ISSUE THREAD

**Issue by dylanmikesell** [jpjones76/SeisIO.jl#80]
I am getting an extra channel returned called XX.FAIL..001. I cannot figure out why this is happening.

```
julia> S = SeisData() # create empty seisdata object
SeisData with 0 channels (0 shown)
    ID: 
  NAME: 
   LOC: 
    FS: 
  GAIN: 
  RESP: 
 UNITS: 
   SRC: 
  MISC: 
 NOTES: 
     T: 
     X: 
        
        
        
        
     C: 0 open, 0 total

julia> get_data!(S, "FDSN", "TA.I07A..BHZ", src="IRIS", s="2006-07-21T00:00:00", t=86400, rr=true)

julia> S
SeisData with 2 channels (2 shown)
    ID: TA.I07A..BHZ                       XX.FAIL..001                       
  NAME: Izee, OR, USA                                                         
   LOC: 44.082 N, -119.504 E, 1293.0 m     0.0 N, 0.0 E, 0.0 m                
    FS: 40.0                               0.0                                
  GAIN: 6.27192e8                          1.0                                
  RESP: a0 3.48462e17, f0 0.2, 6z, 11p     a0 1.0, f0 1.0, 0z, 0p             
 UNITS: m/s                                                                   
   SRC: http://service.iris.edu/fdsnws/da…                                    
  MISC: 4 entries                          3 entries                          
 NOTES: 3 entries                          3 entries                          
     T:                                                                       
     X: (empty)                            (empty)                            
                                                                              
                                                                              
                                                                              
                                                                              
     C: 0 open, 0 total
```

Any ideas why this extra channel shows up? Is this supposed to happen and I am just not aware why? If you trying downloading one day later (s="2006-07-22T00:00:00") this does not happen. Only the BHZ channel is returned. I guess I would have thought that if there is no data, I would just get the first channel (BHZ) and an empty X field.
